export const ATTENDANCE_CONFIG = {
  shifts: {
    title: '班次管理',
    apiKey: 'shifts',
    listPermission: 'attendance:shift:list',
    createPermission: 'attendance:shift:create',
    updatePermission: 'attendance:shift:update',
    deletePermission: 'attendance:shift:delete',
    queryFields: [['name', '班次名称', 'text']],
    columns: [
      ['id', 'ID'],
      ['name', '班次'],
      ['code', '编码'],
      ['start_time', '上班时间'],
      ['end_time', '下班时间'],
      ['late_allowed_minutes', '允许迟到'],
      ['early_leave_allowed_minutes', '允许早退'],
      ['is_cross_day', '跨天', 'boolean'],
      ['is_flexible', '弹性', 'boolean'],
      ['flexible_minutes', '弹性分钟'],
      ['is_active', '状态', 'boolean'],
    ],
    fields: [
      ['name', '班次名称', 'text', true],
      ['code', '班次编码', 'text', true],
      ['start_time', '上班时间', 'time', true],
      ['end_time', '下班时间', 'time', true],
      ['late_allowed_minutes', '允许迟到分钟', 'number'],
      ['early_leave_allowed_minutes', '允许早退分钟', 'number'],
      ['is_cross_day', '跨天', 'boolean'],
      ['is_flexible', '弹性班', 'boolean'],
      ['flexible_minutes', '弹性分钟', 'number'],
      ['is_active', '启用', 'boolean'],
    ],
    empty: () => ({
      name: '',
      code: '',
      start_time: '09:00',
      end_time: '18:00',
      late_allowed_minutes: 0,
      early_leave_allowed_minutes: 0,
      is_cross_day: false,
      is_flexible: false,
      flexible_minutes: 0,
      is_active: true,
    }),
  },
  restRules: {
    title: '休息规则',
    apiKey: 'restRules',
    listPermission: 'attendance:rest-rule:list',
    writePermission: 'attendance:rest-rule:update',
    queryFields: [],
    columns: [
      ['id', 'ID'],
      ['name', '规则名称'],
      ['rest_type', '类型'],
      ['weekday', '星期'],
      ['rest_date', '日期'],
      ['department_ids', '适用部门ID'],
      ['user_ids', '适用员工ID'],
      ['is_active', '状态', 'boolean'],
    ],
    fields: [
      ['name', '规则名称', 'text', true],
      ['rest_type', '类型 fixed/request'],
      ['weekday', '星期 0-6', 'number'],
      ['rest_date', '固定日期', 'date'],
      ['department_ids_text', '适用部门ID列表，逗号分隔'],
      ['user_ids_text', '适用员工ID列表，逗号分隔'],
      ['is_active', '启用', 'boolean'],
    ],
    empty: () => ({ name: '', rest_type: 'fixed', weekday: '', rest_date: '', department_ids_text: '', user_ids_text: '', is_active: true }),
    fillForm(form, row) {
      Object.assign(form, row, {
        department_ids_text: Array.isArray(row.department_ids) ? row.department_ids.join(',') : '',
        user_ids_text: Array.isArray(row.user_ids) ? row.user_ids.join(',') : '',
      })
    },
    toPayload(form) {
      return {
        name: form.name,
        rest_type: form.rest_type || 'fixed',
        weekday: form.weekday === '' || form.weekday === null ? null : Number(form.weekday),
        rest_date: form.rest_date || null,
        department_ids: String(form.department_ids_text || '')
          .split(',')
          .map((item) => Number(item.trim()))
          .filter((item) => item > 0),
        user_ids: String(form.user_ids_text || '')
          .split(',')
          .map((item) => Number(item.trim()))
          .filter((item) => item > 0),
        is_active: form.is_active === true,
      }
    },
  },
  schedules: {
    title: '排班管理',
    apiKey: 'schedules',
    listPermission: 'attendance:schedule:list',
    createPermission: 'attendance:schedule:create',
    updatePermission: 'attendance:schedule:update',
    deletePermission: 'attendance:schedule:delete',
    createMode: 'batch',
    queryFields: [
      ['user_id', '用户ID', 'number'],
      ['department_id', '部门ID', 'number'],
      ['start_date', '开始日期', 'date'],
      ['end_date', '结束日期', 'date'],
    ],
    columns: [
      ['id', 'ID'],
      ['work_date', '日期'],
      ['user_id', '用户ID'],
      ['department_id', '部门ID'],
      ['shift_id', '班次ID'],
      ['source_type', '来源'],
      ['is_temporary', '临时', 'boolean'],
      ['is_swapped', '调班', 'boolean'],
      ['remark', '备注'],
    ],
    fields: [
      ['user_id', '用户ID', 'number', true, 'editOnly'],
      ['user_ids_text', '用户ID列表，逗号分隔', 'text', false, 'createOnly'],
      ['department_id', '部门ID', 'number'],
      ['shift_id', '班次ID', 'number', true],
      ['work_date', '工作日期', 'date', true, 'editOnly'],
      ['start_date', '开始日期', 'date', true, 'createOnly'],
      ['end_date', '结束日期', 'date', true, 'createOnly'],
      ['source_type', '来源 user/department/batch/temporary/swap'],
      ['status', '状态'],
      ['is_temporary', '临时排班', 'boolean'],
      ['is_swapped', '调班', 'boolean'],
      ['remark', '备注'],
    ],
    empty: () => ({
      user_id: '',
      user_ids_text: '',
      department_id: '',
      shift_id: '',
      work_date: '',
      start_date: '',
      end_date: '',
      source_type: 'user',
      status: 'scheduled',
      is_temporary: false,
      is_swapped: false,
      remark: '',
    }),
    toPayload(form, editing) {
      if (editing) {
        return {
          user_id: form.user_id ? Number(form.user_id) : null,
          department_id: form.department_id ? Number(form.department_id) : null,
          shift_id: form.shift_id ? Number(form.shift_id) : null,
          work_date: form.work_date || null,
          source_type: form.source_type || 'user',
          status: form.status || 'scheduled',
          is_temporary: form.is_temporary === true,
          is_swapped: form.is_swapped === true,
          remark: form.remark || null,
        }
      }
      return {
        user_ids: String(form.user_ids_text || '').split(',').map((item) => Number(item.trim())).filter((item) => item > 0),
        department_id: form.department_id ? Number(form.department_id) : null,
        shift_id: Number(form.shift_id),
        start_date: form.start_date,
        end_date: form.end_date,
        source_type: form.source_type || 'user',
        is_temporary: form.is_temporary === true,
        remark: form.remark || null,
      }
    },
  },
  records: {
    title: '打卡记录',
    apiKey: 'records',
    listPermission: 'attendance:record:list',
    createPermission: 'attendance:record:create',
    updatePermission: 'attendance:record:update',
    deletePermission: 'attendance:record:delete',
    queryFields: [
      ['user_id', '用户ID', 'number'],
      ['department_id', '部门ID', 'number'],
      ['start_at', '开始时间', 'datetime-local'],
      ['end_at', '结束时间', 'datetime-local'],
      ['record_type', '记录类型', 'text'],
    ],
    columns: [
      ['id', 'ID'],
      ['user_id', '用户ID'],
      ['shift_id', '班次ID'],
      ['record_type', '类型'],
      ['record_time', '打卡时间', 'datetime'],
      ['source', '来源'],
      ['status', '状态'],
      ['late_minutes', '迟到'],
      ['early_leave_minutes', '早退'],
      ['remark', '备注'],
    ],
    fields: [
      ['user_id', '用户ID', 'number', true],
      ['schedule_item_id', '排班ID', 'number'],
      ['shift_id', '班次ID', 'number'],
      ['record_type', '类型 checkin/checkout/correction', 'text', true],
      ['record_time', '打卡时间', 'datetime-local', true],
      ['source', '来源'],
      ['status', '状态'],
      ['remark', '备注'],
    ],
    empty: () => ({ user_id: '', schedule_item_id: '', shift_id: '', record_type: 'checkin', record_time: '', source: 'manual', status: 'normal', remark: '' }),
  },
  requests: {
    title: '异常申请',
    apiKey: 'requests',
    listPermission: 'attendance:request:list',
    createPermission: 'attendance:request:create',
    updatePermission: 'attendance:request:create',
    queryFields: [
      ['user_id', '用户ID', 'number'],
      ['department_id', '部门ID', 'number'],
      ['request_type', '申请类型', 'text'],
      ['request_status', '申请状态', 'select', [
        ['', '全部'],
        ['pending', '待审批'],
        ['approved', '通过'],
        ['rejected', '驳回'],
        ['withdrawn', '撤回'],
      ]],
    ],
    columns: [
      ['id', 'ID'],
      ['request_no', '申请编号'],
      ['user_id', '用户ID'],
      ['request_type', '类型'],
      ['start_at', '开始', 'datetime'],
      ['end_at', '结束', 'datetime'],
      ['duration_minutes', '分钟'],
      ['status', '状态'],
      ['approver_id', '审批人'],
      ['approval_remark', '审批备注'],
    ],
    fields: [
      ['user_id', '用户ID', 'number', true],
      ['request_type', '类型 correction/leave/outing/overtime/business_trip/rest/compensatory_leave/shift_swap', 'text', true],
      ['start_at', '开始时间', 'datetime-local', true],
      ['end_at', '结束时间', 'datetime-local', true],
      ['related_record_id', '关联记录ID', 'number'],
      ['related_schedule_item_id', '关联排班ID', 'number'],
      ['reason', '原因'],
    ],
    empty: () => ({ user_id: '', request_type: 'correction', start_at: '', end_at: '', related_record_id: '', related_schedule_item_id: '', reason: '' }),
  },
  approvals: {
    title: '审批管理',
    apiKey: 'requests',
    listPermission: 'attendance:approval:list',
    approvePermission: 'attendance:approval:approve',
    readOnly: true,
    defaultQuery: { request_status: 'pending' },
    queryFields: [
      ['user_id', '用户ID', 'number'],
      ['department_id', '部门ID', 'number'],
      ['request_type', '申请类型', 'text'],
    ],
    columns: [
      ['id', 'ID'],
      ['request_no', '申请编号'],
      ['user_id', '用户ID'],
      ['request_type', '类型'],
      ['start_at', '开始', 'datetime'],
      ['end_at', '结束', 'datetime'],
      ['duration_minutes', '分钟'],
      ['reason', '原因'],
      ['status', '状态'],
    ],
  },
  dailyResults: {
    title: '日考勤报表',
    apiKey: 'dailyResults',
    listPermission: 'attendance:daily-report:list',
    readOnly: true,
    rebuild: 'daily',
    queryFields: [
      ['user_id', '用户ID', 'number'],
      ['department_id', '部门ID', 'number'],
      ['start_date', '开始日期', 'date'],
      ['end_date', '结束日期', 'date'],
    ],
    columns: [
      ['id', 'ID'],
      ['work_date', '日期'],
      ['user_id', '用户ID'],
      ['shift_id', '班次ID'],
      ['checkin_time', '上班', 'datetime'],
      ['checkout_time', '下班', 'datetime'],
      ['status', '状态'],
      ['late_minutes', '迟到'],
      ['early_leave_minutes', '早退'],
      ['leave_minutes', '请假'],
      ['overtime_minutes', '加班'],
      ['work_minutes', '出勤'],
    ],
  },
  monthlySummaries: {
    title: '月考勤报表',
    apiKey: 'monthlySummaries',
    listPermission: 'attendance:monthly-report:list',
    readOnly: true,
    rebuild: 'monthly',
    queryFields: [
      ['user_id', '用户ID', 'number'],
      ['department_id', '部门ID', 'number'],
      ['year', '年份', 'number'],
      ['month', '月份', 'number'],
    ],
    columns: [
      ['id', 'ID'],
      ['year', '年'],
      ['month', '月'],
      ['user_id', '用户ID'],
      ['work_days', '应出勤'],
      ['attendance_days', '实出勤'],
      ['late_count', '迟到'],
      ['early_leave_count', '早退'],
      ['missing_count', '缺卡'],
      ['absent_days', '旷工'],
      ['leave_minutes', '请假分钟'],
      ['overtime_minutes', '加班分钟'],
    ],
  },
}
